name: Deploy Auth Backend

on:
  push:
    branches:
      - master
    paths:
      - 'amcart-auth-backend/**'
      - '.github/workflows/deploy-auth-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./amcart-auth-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amcart-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_EC2_HOST }}
          username: ${{ secrets.BACKEND_EC2_USER }}
          key: ${{ secrets.BACKEND_EC2_SSH_KEY }}
          debug: true
          script: |
            echo "connected"